### ISSUE TITLE
Implement package for diff drive robot

### ISSUE THREAD

**Issue by holmbuar** [PickNikRobotics/topic_based_ros2_control#15]
I have made a working hardware component for a diff drive robot, based on the [ROS2 control demo](https://github.com/ros-controls/ros2_control_demos/tree/humble/example_2). I even set up a communication ROS2 node to my microcontroller _inside_ the HW interface, which I later learned was bad practice. 

I was pointed to this package, installed the `apt` version, and now I'm trying to understand how I can use it in my ROS2 `humble` based project. 

After adding the plugin to `ros2_control.xacro`,
```
<hardware>
  <plugin>topic_based_ros2_control/TopicBasedSystem</plugin>
  <param name="joint_commands_topic">/diffbot_joint_commands</param>
  <param name="joint_states_topic">/diffbot_joint_states</param>
  <param name="trigger_joint_command_threshold">0.001</param>
  <param name="sum_wrapped_joint_states">false</param>
</hardware>
```
I can build and launch the diffbot, and the topics show up on `ros2 topic list`. However, I'm not quite sure how to start reading and writing joint states, using this package. 

Including the package in my `diffbot_system.cpp` 
```
#include "topic_based_ros2_control/topic_based_system.hpp"
```
`colcon build` yields
```
fatal error: topic_based_ros2_control/topic_based_system.hpp: No such file or directory
   36 | #include "topic_based_ros2_control/topic_based_system.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

In my CMakeLists.txt:
```
# find dependencies
set(THIS_PACKAGE_INCLUDE_DEPENDS
  hardware_interface
  pluginlib
  rclcpp
  rclcpp_lifecycle
  topic_based_ros2_control
)
```

In my package.xml:
```
<depend>topic_based_ros2_control</depend>
```
Also tried
```
rosdep install --ignore-src --from-paths . -y
colcon build --symlink-install --event-handlers log-
source install/local_setup.bash 
```

@JafarAbdi I would greatly appreciate some pointers to correct my path.

**Comment by JafarAbdi** [comment]
You don't need to include this package in your system, this package will work with robots that uses topics to control the robot/publish its state, can you add more info about your system/robot?

Tagging @MarqRazz since he worked on something similar in the past!

**Comment by MarqRazz** [comment]
The only dependency you should need to list is in the package.xml `<depend>topic_based_ros2_control</depend>`.

- After that you include the plugin in the [ros2_contro.xacro](https://github.com/MarqRazz/c3pzero/blob/main/c300/c300_description/urdf/c300.ros2_control.xacro#L15-L20)
- Make a [controllers.yaml](https://github.com/MarqRazz/c3pzero/blob/main/c300/c300_bringup/config/c300_isaac_controllers.yaml) if you want to use the DiffDriveController
- And then launch the [controller_manager](https://github.com/MarqRazz/c3pzero/blob/main/c300/c300_bringup/launch/isaac_c300.launch.py#L138) and any [controllers](https://github.com/MarqRazz/c3pzero/blob/main/c300/c300_bringup/launch/isaac_c300.launch.py#L194) you require.


After you get everything started you should see the hardware interfaces started when you bring up your robot and topics should be available on the names you specified in the ros2_control.xacro.

**Comment by n0sc3tipsum** [comment]
Hi, I have a very similar setup. 

I was able to launch the controller manager, and I'm using the joint state broadcaster (joint_broad) and the differential drive controller (diff_cont). I can see the topics that I specified for the state and command interface yet when I try echo them I can't seem to get anything. 

![PHOTO-2024-06-13-16-39-41](https://github.com/PickNikRobotics/topic_based_ros2_control/assets/131246875/b08b2990-bde4-4f4e-a60f-2bae0850b129)

The above pic shows the rqt_graph for my ROS2 system. 

The way I understand it is that the diffDriveController will use the interfaces from the topic_based_ros2_control plugin which would relay the joint control commands onto the /joint_ctrl topic that I specified - yet when I use a teleop_twist_keyboard to send in command velocities onto the /manual_cmd_vel topic, I don't see anything on the /joint_ctrl topic, but I can see those command velocities being relayed to the /diff_cont/cmd_vel_unstamped topic.

Im not sure what I'm missing.

Thanks!

**Comment by JafarAbdi** [comment]
> Hi, I have a very similar setup.
> 
> I was able to launch the controller manager, and I'm using the joint state broadcaster (joint_broad) and the differential drive controller (diff_cont). I can see the topics that I specified for the state and command interface yet when I try echo them I can't seem to get anything.
> 
> ![PHOTO-2024-06-13-16-39-41](https://github.com/PickNikRobotics/topic_based_ros2_control/assets/131246875/b08b2990-bde4-4f4e-a60f-2bae0850b129)
> 
> The above pic shows the rqt_graph for my ROS2 system.
> 
> The way I understand it is that the diffDriveController will use the interfaces from the topic_based_ros2_control plugin which would relay the joint control commands onto the /joint_ctrl topic that I specified - yet when I use a teleop_twist_keyboard to send in command velocities onto the /manual_cmd_vel topic, I don't see anything on the /joint_ctrl topic, but I can see those command velocities being relayed to the /diff_cont/cmd_vel_unstamped topic.
> 
> Im not sure what I'm missing.
> 
> Thanks!

Please open a new if you stil can't move the robot.

Closing this issue!
