### ISSUE TITLE
Very high frequency

### ISSUE THREAD

**Issue by muttistefano** [PickNikRobotics/topic_based_ros2_control#17]
Hi all, i am using the topic hardware interface to move multiple robots in gazebo, using the plugin in this way: 
```     
<hardware>
          <plugin>topic_based_ros2_control/TopicBasedSystem</plugin>   
          <param name="joint_commands_topic">joint_commands</param>   
          <param name="joint_states_topic">jnt_gz</param>   
          <param name="sum_wrapped_joint_states">false</param>   
</hardware>
```

I noticed that the /joint_commands topic is published at a frequency of almost 10000Hz.
Is there a way to modify this?
The controller manager update rati is set to 50.
Thanks

**Comment by JafarAbdi** [comment]
Hi, do you mind sharing your ros2 control yaml file? In theory, it shouldn't run at higher frequency than the controller manager

**Comment by muttistefano** [comment]
Hi @JafarAbdi and thanks for the quick response.
The controller file is: https://github.com/muttistefano/lampo_description/blob/master/config/ur_controllers_1.yaml
While the plugin is loaded here: https://github.com/muttistefano/lampo_description/blob/master/urdf/system.urdf.xacro

Thanks

**Comment by peterdavidfagan** [comment]
I am also finding that the frequency at which command messages are published, exceeds that of the controller manager.

**Comment by muttistefano** [comment]
Hi , sorry for the late reply, i might have missed the mail.
I am indeed using the sim_time.
I will give it a try without it.
Thanks

**Comment by JafarAbdi** [comment]
Looks like more of a ros2_control issue than topic_based_ros2_control, closing for now. Please feel free to re-open
