### ISSUE TITLE
What should the topic data look like?

### ISSUE THREAD

**Issue by anthonywebb** [PickNikRobotics/topic_based_ros2_control#18]
This seems like it could be a great fit for people who don't want to write a custom hardware interface for ros2_control (which if you are not a c++ guru, is a steep ask) 

We use motor controllers from odrive.  They have a package that talks to their controllers over canbus and provides topics as an interface to their motor drivers. https://github.com/odriverobotics/odrive_can

If I can understand what the topic(s) should look like in order to use topic_based_ros2_control I think I could tweak their package to work.  Can someone help me understand what the data in/out of these topics that topic_based_ros2_control points to should look like?

**Comment by JafarAbdi** [comment]
This package expects you to use a topic with `sensor_msgs::msg::JointState` type for specifying the joint commands/joint states, I think your case it's better to implement an interface similar to the dynamixal motors see https://github.com/dynamixel-community/dynamixel_hardware
